#include <iostream>
#include <cctype>
using namespace std;

int main(){
  //1.
  // cout<<"Enter the number: ";
  // int number;
  // cin >> number;

  // if ((number % 4 == 0 && number % 100 != 0) || (number % 400 == 0)) {
  //   cout <<"Leap year";
  // }
  // else{
  //   cout <<"Not a leap year";
  // }

  //2.
  // int n = 4;

  // for(int i = 1; i<=n; i++){
  //   for(int j =1;j<=i; j++){
  //     cout << "*";
  //   }
  //   cout << endl;
  // }

  //3.
  // int n = 4;
  // for(int i = 1; i <=n; i++){
  //   for(int j = 1; j<=i;j++){
  //     cout << j;
  //   }
  //   cout << endl;
  // }

  //4.
  // int n;
  // cout << "Enter the number: ";
  // cin >> n;

  // if(n > 0){
  //   while()
  // }

  //5.
  // int n, p = 1;
  // cout << "Enter the number: ";
  // cin >> n;

  // while(p<=n){
  //   cout<<p;
  //   if(p % 2 == 0){
  //     cout << "Even" << endl;
  //   }
  //   else{
  //     cout << "Odd" << endl;
  //   }
  //   p++;
  // }

  //6.
  // int n = 5;
  // for(int i = 1; i<=n; i++){
  //   for(int j=1;j<=n-i+1;j++){
  //     cout << "*";
  //   }
  //   cout << endl;
  // }

  //7.
  // char n;
  // cout << "Enter the number: ";
  // cin >> n;
  // if(isupper(n)){
  //   cout << "Upper case" << endl;
  // } else if(islower(n)) {
  //   cout << "Lower case" << endl;
  // } else if(isdigit(n)){
  //   cout << "0-9" << endl;
  // }else{
  //   cout << "Special character" << endl;
  // }
  
  //8.
  int n;
  cout << "Enter the number: ";
  cin >> n;
  int sum = 0;
  while(n > 0){
  int digit =;
}